# Generated by Django 4.1.6 on 2023-05-05 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_recipeingredientamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_code', message='Введите код цвета в формате HEX', regex='^#([A-Fa-f0-9]{3,6}$')]),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredientamount', verbose_name='Ингредиенты'),
            preserve_default=False,
        ),
    ]
