# Generated by Django 4.1.6 on 2023-05-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipes_ingredients_alter_tag_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.ingredientamount', verbose_name='Ингредиенты'),
        ),
    ]
