# Generated by Django 4.1.7 on 2023-05-21 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_alter_favourite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_code', message='Введите код цвета в формате HEX', regex='^#([A-Fa-f0-9]{3,6})$')]),
        ),
    ]
